const category = [
  {
    id: 1,
    name: "Horror",
  },
  {
    id: 2,
    name: "Fantasy",
  },
  {
    id: 3,
    name: "Detective",
  },
  {
    id: 4,
    name: "Romance",
  },
  {
    id: 5,
    name: "Science Fiction",
  },
];

const books = [
  {
    id: 1,
    name: "Dracula",
    autor: "Bram Stoker",
    bookCover: "/images/bookCover/dracula.png",
    categoryId: 1,
    isNew: false,
    isPopular: true,
  },
  {
    id: 2,
    name: "Не твоя Людмила",
    autor: "Лира Алая",
    bookCover: "/images/bookCover/Не твоя Людмила.png",
    categoryId: 1,
    isNew: false,
    isPopular: true,
  },
  {
    id: 3,
    name: "It",
    autor: "Stephen King",
    bookCover: "/images/bookCover/it.png",
    categoryId: 1,
    isNew: true,
    isPopular: true,
  },
  {
    id: 4,
    name: "The Hobbit",
    autor: "J.R.R. Tolkien",
    bookCover: "/images/bookCover/hobbit.png",
    categoryId: 2,
    isNew: false,
    isPopular: true,
  },
  {
    id: 5,
    name: "Harry Potter and the Sorcerer’s Stone",
    autor: "J.K. Rowling",
    bookCover: "/images/bookCover/harry-potter-1.png",
    categoryId: 2,
    isNew: false,
    isPopular: true,
  },
  {
    id: 6,
    name: "Sherlock Holmes: A Study in Scarlet",
    autor: "Arthur Conan Doyle",
    bookCover: "/images/bookCover/sherlock-holmes.png",
    categoryId: 3,
    isNew: false,
    isPopular: true,
  },
  {
    id: 7,
    name: "Murder on the Orient Express",
    autor: "Agatha Christie",
    bookCover: "/images/bookCover/orient-express.png",
    categoryId: 3,
    isNew: false,
    isPopular: true,
  },
  {
    id: 8,
    name: "Pride and Prejudice",
    autor: "Jane Austen",
    bookCover: "/images/bookCover/pride-prejudice.png",
    categoryId: 4,
    isNew: false,
    isPopular: true,
  },
  {
    id: 9,
    name: "The Fault in Our Stars",
    autor: "John Green",
    bookCover: "/images/bookCover/fault-in-our-stars.png",
    categoryId: 4,
    isNew: true,
    isPopular: true,
  },
  {
    id: 10,
    name: "Dune",
    autor: "Frank Herbert",
    bookCover: "/images/bookCover/dune.png",
    categoryId: 5,
    isNew: false,
    isPopular: true,
  },
  {
    id: 11,
    name: "1984",
    autor: "George Orwell",
    bookCover: "/images/bookCover/1984.png",
    categoryId: 5,
    isNew: false,
    isPopular: true,
  },
  {
    id: 12,
    name: "Project Hail Mary",
    autor: "Andy Weir",
    bookCover: "/images/bookCover/project-hail-mary.png",
    categoryId: 5,
    isNew: true,
    isPopular: true,
  },
];
